version: "3.8"
services:
  movies:
    image: girishma31/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: girishma31/trainrepo:latest
    ports:
      - 82/80
    deploy:
      replicas: 3
  dth:
    image: girishma31/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge: null
    image: girishma31/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3

   
